### ISSUE TITLE
hi, i need a teammate

### ISSUE THREAD

**Issue by abdouahabch7** [Gauraaaaaaaa/Energizer-1.20.1#1]
i was scrolling in mods at modrinth and i found your mod, i looked at it and when i entered your user i saw that its your first mod
**so** i want you to become a member at https://modrinth.com/organization/phoenix-eternal-flames and post new projects in it 
this is my discord server https://discord.gg/6p6TsgSB enter and we gonna talk about more informations

**Comment by Gauraaaaaaaa** [comment]
Hello,

I am not interested in your proposition,

Sorry.

**Comment by abdouahabch7** [comment]
its okay and thank you
