### ISSUE TITLE
Minor Suggestion

### ISSUE THREAD

**Issue by tylrcodes** [Gauraaaaaaaa/Energizer-1.20.1#10]
Since your mod handles food healing in a separate way, mods like [Appleskin](https://modrinth.com/mod/appleskin/versions) won't show the health regeneration display overlay when hunger is disabled.
![jUOKFUl](https://github.com/user-attachments/assets/2bac4c40-c364-47bf-9251-e47bee3023f4)

So, I was thinking maybe you could incorporate a feature like this into your mod! Basically, when holding a food item, it could flash display the amount of health that would be healed over the player's health bar.

**Comment by Gauraaaaaaaa** [comment]
This feature will be a great addition!

I also planned to make a list of all the foods to choose what amount of health will be restored.
I want it to be fully compatible with any mods that add foods.

So it will take me some time...

**Comment by Gauraaaaaaaa** [comment]
Damn... 1 month... But there it is!

**Comment by Gauraaaaaaaa** [comment]
I had to copy-paste the original Health Bar code to insert my part for this animation and then cancel the original code.
So it may have some issues with other mods...
