### ISSUE TITLE
Peaceful Mode Stamina

### ISSUE THREAD

**Issue by eithli** [Gauraaaaaaaa/Energizer-1.20.1#12]
Quick suggestion! It would be a nice QoL feature if stamina were disabled in peaceful mode while keeping the disabled hunger toggle, with food healing directly restoring your health—there should be a toggle for this, of course.

Reasoning: I’m making a “vanilla+” mod pack and trying to polish it 100%, so small miscellaneous features like this would be a nice addition. Thanks again for your hard work on this mod—no pressure!

**Comment by Gauraaaaaaaa** [comment]
Hi!

Done in 1.3.0 version.
You can now find an option (in Stamina section) to disable/enable Stamina in Peaceful!
