### ISSUE TITLE
Few Bugs [1.20.1 Fabric]

### ISSUE THREAD

**Issue by tylrcodes** [Gauraaaaaaaa/Energizer-1.20.1#14]
Bug #1: It seems that the fix for not being able to sprint in creative mode when stamina is depleted in survival mode has been bugged again. Essentially, the same issue persists: a player cannot sprint in creative mode until they switch to survival mode and wait for their stamina to refill. After that, they can switch back to creative mode and sprint.

Bug #2: Foods cannot be infinitely eaten in creative mode unless the player has lost some health in survival mode.

**Comment by Gauraaaaaaaa** [comment]
Hi!

Fix in 1.3.1 version.
My stamina and food mechanics no longer influence the creative mode!

**Comment by SrMast3r** [comment]
Is it possible to suggest something?

As an example, you can recover your Stamina by drinking water with the minecraft:potion.
