### ISSUE TITLE
Moriya's Mods incompatibilities: Hearty Meal, Potion Sauce, Enchancement

### ISSUE THREAD

**Issue by TwentySeventhLetter** [Gauraaaaaaaa/Energizer-1.20.1#2]
Hello,

First, I wanted to say I love the mod! It's a great concept that I've been dying to see in a modern version so I was super excited when I caught this on the mod launcher.
That said, I attempted to run a couple of mods on Minecraft 1.20.1 Fabric 0.15.11 with it, and it seemed like this one was being quite aggressive with the changes it makes to Vanilla files. I wanted to use the Energizer stamina system but leave the healing effects up to the Hearty Meal mod by MoriyaShiine, and when installing both mods the game crashed before it started. Similarly, running Energizer made it so Potion Sauce (by the same creator) would be functionally useless; I could not place food items into brewing stands like that mod is supposed to allow. One other smaller issue was that when attempting to bind the Sprint or Sneak buttons to other functions, in my case the enchantment abilities from Moriya's Enchancement mod, the keys do nothing at all when bound to 2 or more inputs. These seem like things which should conceptually be compatible, could you look into what the issue is? Thank you!

**Comment by Gauraaaaaaaa** [comment]
Hello,

Thank you for your return !

I fixed the issue with the **Hearty Meals** mod. I highly recommend turning off the _move armor bar_ option in the client section in the config of this mod. It will prevent the stamina bar and the armor bar from overlapping.

However, the **Potion Sauce** and **Enchancement** mods work well for me... My mod doesn't touch any keybinds, so there should not be a problem with inputs...

I hope this will help !

**Comment by TwentySeventhLetter** [comment]
That's fantastic! I'll do some more testing with the other bugs I encountered, I only noticed those issues when I added your mod but I realize I also had to update my Fabric version so it's probably something to do with that. The Hearty Meals thing was the main problem though so I'm super excited to play with all of the mods on!
