### ISSUE TITLE
Stamina bar still renders while riding a mount

### ISSUE THREAD

**Issue by TwentySeventhLetter** [Gauraaaaaaaa/Energizer-1.20.1#3]
Hi again! I just realized that the Energizer lightning bolts still render even when riding a mount, they just show up behind the saddle hearts. I think they should probably just not load when riding a mount (since you can't use them while mounted anyway).

**Comment by Gauraaaaaaaa** [comment]
You're right !

No sooner said than done, the Stamina bar is not showing anymore when riding entities !
