### ISSUE TITLE
[SUGGESTION] Hunger and Stamina Bar + Dehydration Support

### ISSUE THREAD

**Issue by DaDiGui** [Gauraaaaaaaa/Energizer-1.20.1#4]
Hello, would it be possible to add an option to separate the food and stamina bar so that they work independently? Also add support for [Dehydration](https://modrinth.com/mod/dehydration)
Thanks in advance!

**Comment by Gauraaaaaaaa** [comment]
Hello,

I uploaded a new version (1.0.0) where you can enable/disable Hunger.

For [Dehydration](https://modrinth.com/mod/dehydration), I added more options for positioning the Hunger and Air bars so you can place them where you want.

Please, let me know if there are any other issues !
