### ISSUE TITLE
[Sinytra Connector] Compatibility

### ISSUE THREAD

**Issue by DaDiGui** [Gauraaaaaaaa/Energizer-1.20.1#5]
Hi, I just wanted to let you know that I created this discussion in [Mod Compatibility Thread](https://github.com/Sinytra/Connector/issues/1150) on Sinytra Connector. Maybe you can help to see why the client crashes.

**Comment by Gauraaaaaaaa** [comment]
Hi,

I uploaded a new version (1.1.1) which modifies the mixins for the Air bar not to use "_ModifyArg_" but "_Redirect_" instead. Maybe it was that who crashed the game with Sinytra Connector...

I hope this will help!

**Comment by DaDiGui** [comment]
Keep crashing, here is the log:
https://mclo.gs/uzlLR9s

**Comment by Gauraaaaaaaa** [comment]
I don't know Forge or Sinytra Connector very well, I can't help anymore, sorry...
