### ISSUE TITLE
Stamina resets on relog

### ISSUE THREAD

**Issue by TwentySeventhLetter** [Gauraaaaaaaa/Energizer-1.20.1#6]
Hi again! I noticed that whenever you enter a world, whatever your stamina was when you logged off is completely disregarded, meaning that whether you were at full stamina or completely empty on cooldown due to sprinting too much, you start at 0 stamina and it recharges like normal. Initially I thought this was intended (and maybe it is), but specifically the interaction with the cooldown mechanic feels ripe for abuse.

If your stamina is red and you're in a tricky situation, you can just relog and sprint almost instantly again, so imo it should remember your current stamina status when leaving and reentering the world.

**Comment by Gauraaaaaaaa** [comment]
Fix in 1.2.0 version

**Comment by TwentySeventhLetter** [comment]
Awesome!
