### ISSUE TITLE
Customizable settings for swimming

### ISSUE THREAD

**Issue by TwentySeventhLetter** [Gauraaaaaaaa/Energizer-1.20.1#7]
A thought I had was to add a config feature to modify the sprinting coefficients for swimming, in case you want swimming to be more or less exhausting than land sprinting, or simply make swimming not cost stamina. Not sure of the scope of this feature but figured I'd suggest it!

**Comment by Gauraaaaaaaa** [comment]
Hi! I initially planned to do this at the beginning but forgot about it... Thanks for reminding me!
Add in 1.2.0 version

**Comment by TwentySeventhLetter** [comment]
Haha, that's fantastic, thanks a ton!
