### ISSUE TITLE
Few Issues I've Came Across.

### ISSUE THREAD

**Issue by tylrcodes** [Gauraaaaaaaa/Energizer-1.20.1#8]
Pretty self-explanatory so I'll list them below.

#1 - If a player runs out of stamina in survival mode they won't be able to sprint in creative until they've waited it out to replenish in survival.

#2 - If hunger is disabled, even if the player is already at full health, they can continue to eat.

That's basically about it, though I have 2 minor suggestions: Add a delay config option for the time it takes to start replenishing the stamina bar after sprinting/swimming & an option to disable the inability to sprint at all if the bar has hit zero/and having to wait till it fully fills.

Just wanna say that I love the mod, so keep up the great work!

**Comment by Gauraaaaaaaa** [comment]
Hi!
Thank you for your return!
The issues are fixed in the newer version. I also implemented your suggestions!
