### ISSUE TITLE
Incompatibility with Nostalgic Tweaks

### ISSUE THREAD

**Issue by SimplyTadpole** [Gauraaaaaaaa/Energizer-1.20.1#9]
Hello! I wanted to use your mod for a beta-style modpack I'm making because I want to retain the ability to sprint but keep it balanced for a game without hunger, and I'm already using Nostalgic Tweaks for other purposes. Unfortunately, using both at the same time causes a crash due to a mixin conflict.

I know it's an incompatibility between both specifically, because removing either of them lets the game load successfully.

This is my crash log: https://mclo.gs/clKgMjo

**Comment by Gauraaaaaaaa** [comment]
Hi!
I tried many things but the main issue is how they made Nostalgic Tweaks...
However, I found a solution: the Hunger and Air Bars mixins are disabled if Nostalgic Tweaks is installed. So every setting that touches Hunger and Air Bars will do nothing.
Let me know if there are any other issues!

**Comment by SimplyTadpole** [comment]
Hey, thanks for the fix!

It now loads successfully and I'm able to use them without issues - unfortunately, when armour is equipped, the armour bar appears underneath the stamina bar, making it impossible to view it.

Given what you said, I don't think it's possible to adjust the armour bar to render above the stamina bar without causing it to break compatibility with NT again, but I have an idea: maybe you could add an option specifically for usage alongside Nostalgic Tweaks which, when enabled, shifts the stamina bar upward by a specific Y value whenever the player is wearing anything that adds armour/defense values?

**Comment by Gauraaaaaaaa** [comment]
Hi!

Effectively, I cannot change the position of the Armor Bar due to Nostalgic Tweaks...
But I will try your idea.

**Comment by SimplyTadpole** [comment]
So, I came up with a silly workaround for this issue...

Make a resource pack (or edit an existing one) that makes the hunger bar invisible, then in Nostalgic Tweaks keep the Hunger Bar enabled but disable Hunger mechanics.

This way, the Armour Bar will properly render above the Health Bar while the Air Bar renders on top of the Stamina Bar. It's a silly fix, but it works, so I guess it's all good now. Regardless, thank you for your work in making the mod compatible with Nostalgic Tweaks!

![image](https://github.com/user-attachments/assets/b0b473a0-5acb-43f9-8197-6637452c3c5c)

**Comment by Gauraaaaaaaa** [comment]
Glad you found a solution!
